### ISSUE TITLE
Paper file not found

### ISSUE THREAD

**Issue by wangzhanwei666** [snkas/hypatia#1]
When access https://polybox.ethz.ch/index.php/s/9G7ViXyvtkeTqJj in the browser, the polybox website only output a box "File not found The specified document has not been found on the server. You can click here to return to polybox."

How can I get the paper data?

**Comment by snkas** [comment]
Ah, it appears that the public link on the Polybox changed.

New link:
https://polybox.ethz.ch/index.php/s/Y35PwifNOKkcnvR

For convenience, the SHA-256 checksum:
18d761a28706723b57772e0636fbc40b7d57161f4c54069eede0c8ae740cbe2d
