### ISSUE TITLE
Building Hypatia : Build failed with exit status 1

### ISSUE THREAD

**Issue by abx13** [snkas/hypatia#12]
Hello,

After having installed the prerequisites and the dependencies as explained in Hypatia's READ.ME, we have a problem when trying to build Hypatia.

Here is what is displayed. How could we fix it?

![Screenshot_Hypatia_Builed_Failed_Exit_Status_1](https://user-images.githubusercontent.com/48131851/168074100-d16459da-10ae-49af-b1bb-7f959a52d78c.png)

**Comment by snkas** [comment]
Hi,

It could be that you are using a newer or different C++ compiler than the default of Ubuntu 18.04 in which Hypatia was released.

**Comment by abx13** [comment]
Thank you very much!
 What version of python did you use when Hypatia was released?
Because we did try installing it first with Ubuntu 18.04 and python3.10 but we had problems installing dependencies. With Ubuntu22.04 there is no problem with the dependencies but we can't successfully build the program.

**Comment by abx13** [comment]
Perfect! It did build with Ubuntu 20.04 and python 3.8. Thank you for your help!

**Comment by tkoch96** [comment]
I fixed this error  --- I turned off "-Werror" in the compilation. Look at ns3-sat-sim/simulator/waf-tools/cflags.py on line 162.
