### ISSUE TITLE
`visualize_constellation.py` cannot generate constellation

### ISSUE THREAD

**Issue by ShiGuangzhao** [snkas/hypatia#3]
hello, I am using `visualize_constellation.py` to generates dynamic visualizations for entire constellation (multiple shells). However, when I open the output HTML file in Google Chrome, there is only the earth and no constellations in the webpage.

I found through debugging that a `Failed to load resource: net::ERR_FAILED` error occurred when loading the json file. This problem was solved by opening the file with the Live Server plug-in of VS Code. 

Then the error of `Failed to load resource: net::ERR_CONNECTION_RESET` appeared at this time. It seems that there was an error in parsing the JSON file? The details are shown in the figure. Could you help me with this problem? 
Thank you.

Shi Guangzhao

![image](https://user-images.githubusercontent.com/39906009/114279350-c2c58b80-9a66-11eb-9151-f683810767ce.png)

**Comment by puyanguvic** [comment]
Hi, I have a similar problem as yours when visualizing the constellation. Have you solved the problem?
Thank you!

**Comment by ZhengYuNing8988** [comment]
I also meet the problem that only the earth but not Starlink .And I use "live sever" also cannot solve the problem.

**Comment by debopambhattacherjee** [comment]
Please download the latest version of the code and check if the problem has been fixed. We have stopped using JSON objects for constellation visualization.
