### ISSUE TITLE
The html files generated by the SatViz module cannot be opened

### ISSUE THREAD

**Issue by dddyx** [snkas/hypatia#5]
Hello, I am having a problem. I ran `visualize_constellation.py` following the steps in `<hypatia>/satviz/README.md`. But the resulting html files are blank when opened. Also the website you gave https://leosatsim.github.io/Starlink_3D.html cannot open, is there something wrong with my steps?

**Comment by bdebopam** [comment]
Hi, yes we are aware of this issue on Chrome. Could you try using Firefox instead?

**Comment by dddyx** [comment]
Thank you for your reply :) . I have tried to open it with Firefox, but it still cannot open. Do I need to do some additional configuration to the browser?

**Comment by bdebopam** [comment]
Can you share the console error log that you see in firefox? Alternatively, try toggling the config param strict_origin_policy. Note that we do recommend the default value of the parameter for continued browsing on firefox.

**Comment by dddyx** [comment]
Thank you for your reply :) . I found that it was due to the use of proxy server. When I turned off the web proxy, it opened.
