### ISSUE TITLE
In Step 1,the code has been running for about 20 hours, is it normal?

### ISSUE THREAD

**Issue by zty19981212** [snkas/hypatia#9]
## Steps to run

**Step 1: generating LEO satellite network dynamic state over time**

Instructions can be found in `<hypatia>/paper/satellite_networks_state/README.md`

**Step 2: build ns-3 simulator**

Instructions can be found in `<hypatia>/ns3-sat-sim/README.md`

**Step 3: performing analysis using satgenpy**

Instructions can be found in `<hypatia>/paper/satgenpy_analysis/README.md`

**Step 4: running ns-3 experiments**

Instructions can be found in `<hypatia>/paper/ns3_experiments/README.md`

**Step 5: generating satviz figures**

Instructions can be found in `<hypatia>/satviz/README.md` under `Visualizations in the paper`.

**Comment by snkas** [comment]
Please see the text above the steps you posted: https://github.com/snkas/hypatia/blob/master/paper/README.md
